-- Create Room Trigger

CREATE TRIGGER ROOM_INSERT
    AFTER INSERT
    ON ROOMS
    FOR EACH ROW
BEGIN
    INSERT INTO ROOMS_AUD (EVENT_DATE, EVENT_TYPE, ROOM_ID, NEW_ROOM_NAME, NEW_ROOM_SEATS)
        VALUE (CURTIME(), 'INSERT', NEW.ROOM_ID, NEW.ROOM_NAME, NEW.ROOM_SEATS);
END;

-- Delete Room Trigger

CREATE TRIGGER ROOM_DELETE
    AFTER DELETE
    ON ROOMS
    FOR EACH ROW
BEGIN
    INSERT INTO ROOMS_AUD (EVENT_DATE, EVENT_TYPE, ROOM_ID, OLD_ROOM_NAME, OLD_ROOM_SEATS) -- [3]
        VALUE (CURTIME(), 'DELETE', OLD.ROOM_ID, OLD.ROOM_NAME, OLD.ROOM_SEATS);
END;

-- Update Room Trigger

CREATE TRIGGER ROOM_UPDATE
    AFTER UPDATE
    ON ROOMS
    FOR EACH ROW
BEGIN
    INSERT INTO ROOMS_AUD (EVENT_DATE, EVENT_TYPE, ROOM_ID, OLD_ROOM_NAME, NEW_ROOM_NAME, OLD_ROOM_SEATS,
                           NEW_ROOM_SEATS) -- [3]
        VALUE (CURTIME(), 'UPDATE', OLD.ROOM_ID, OLD.ROOM_NAME, NEW.ROOM_NAME, OLD.ROOM_SEATS, NEW.ROOM_SEATS);
END;

-- Create Employee Trigger

CREATE TRIGGER EMPLOYEES_INSERT
    AFTER INSERT
    ON EMPLOYEES
    FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEES_AUD (EVENT_DATE, EVENT_TYPE, EMPLOYEE_ID, NEW_FIRST_NAME, NEW_LAST_NAME)
        VALUE (CURTIME(), 'INSERT', NEW.EMPLOYEE_ID, NEW.FIRST_NAME, NEW.LAST_NAME);
END;

-- Delete Employee Trigger

CREATE TRIGGER EMPLOYEES_DELETE
    AFTER DELETE
    ON EMPLOYEES
    FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEES_AUD (EVENT_DATE, EVENT_TYPE, EMPLOYEE_ID, OLD_FIRST_NAME, OLD_LAST_NAME)
        VALUE (CURTIME(), 'DELETE', OLD.EMPLOYEE_ID, OLD.FIRST_NAME, OLD.LAST_NAME);
END;

-- Update Employee Trigger

CREATE TRIGGER EMPLOYEES_UPDATE
    AFTER UPDATE
    ON EMPLOYEES
    FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEES_AUD (EVENT_DATE, EVENT_TYPE, EMPLOYEE_ID, OLD_FIRST_NAME, NEW_FIRST_NAME, OLD_LAST_NAME,
                               NEW_LAST_NAME)
        VALUE (CURTIME(), 'UPDATE', OLD.EMPLOYEE_ID, OLD.FIRST_NAME, NEW.FIRST_NAME, OLD.LAST_NAME,
               NEW.LAST_NAME);
END;

-- Create Movie Trigger

CREATE TRIGGER MOVIES_INSERT
    AFTER INSERT
    ON MOVIES
    FOR EACH ROW
BEGIN
    INSERT INTO MOVIES_AUD (EVENT_DATE, EVENT_TYPE, MOVIE_ID, NEW_TITLE, NEW_DESCRIPTION, NEW_YEAR)
        VALUE (CURTIME(), 'INSERT', NEW.MOVIE_ID, NEW.TITLE, NEW.DESCRIPTION, NEW.YEAR);
END;

-- Delete Movie Trigger

CREATE TRIGGER MOVIES_DELETE
    AFTER DELETE
    ON MOVIES
    FOR EACH ROW
BEGIN
    INSERT INTO MOVIES_AUD (EVENT_DATE, EVENT_TYPE, MOVIE_ID, OLD_TITLE, OLD_DESCRIPTION, OLD_YEAR)
        VALUE (CURTIME(), 'DELETE', OLD.MOVIE_ID, OLD.TITLE, OLD.DESCRIPTION, OLD.YEAR);
END;

-- Update Movie Trigger

CREATE TRIGGER MOVIES_UPDATE
    AFTER UPDATE
    ON MOVIES
    FOR EACH ROW
BEGIN
    INSERT INTO MOVIES_AUD (EVENT_DATE, EVENT_TYPE, MOVIE_ID, OLD_TITLE, NEW_TITLE, OLD_DESCRIPTION,
                            NEW_DESCRIPTION, OLD_YEAR, NEW_YEAR)
        VALUE (CURTIME(), 'UPDATE', OLD.MOVIE_ID, OLD.TITLE, NEW.TITLE, OLD.DESCRIPTION,
               NEW.DESCRIPTION, OLD.YEAR, NEW.YEAR);
END;

-- Create Performance Trigger

CREATE TRIGGER PERFORMANCES_INSERT
    AFTER INSERT
    ON PERFORMANCES
    FOR EACH ROW
BEGIN
    INSERT INTO PERFORMANCES_AUD (EVENT_DATE, EVENT_TYPE, PERFORMANCE_ID, NEW_DATE, NEW_TIME,
                                  NEW_MOVIE_ID, NEW_ROOM_ID)
        VALUE(CURTIME(), 'INSERT', NEW.PERFORMANCE_ID, NEW.DATE, NEW.TIME, NEW.MOVIE_ID, NEW.ROOM_ID);
END;

-- Delete Performance Trigger

CREATE TRIGGER PERFORMANCES_DELETE
    AFTER DELETE
    ON PERFORMANCES
    FOR EACH ROW
BEGIN
    INSERT INTO PERFORMANCES_AUD (EVENT_DATE, EVENT_TYPE, PERFORMANCE_ID, OLD_DATE,
                                  OLD_TIME, OLD_MOVIE_ID,  OLD_ROOM_ID)
        VALUE(CURTIME(), 'DELETE', OLD.PERFORMANCE_ID, OLD.DATE, OLD.TIME,
              OLD.MOVIE_ID, OLD.ROOM_ID);
END;

-- Update Performance Trigger

CREATE TRIGGER PERFORMANCES_UPDATE
    AFTER UPDATE
    ON PERFORMANCES
    FOR EACH ROW
BEGIN
    INSERT INTO PERFORMANCES_AUD (EVENT_DATE, EVENT_TYPE, PERFORMANCE_ID, OLD_DATE, NEW_DATE,
                                  OLD_TIME, NEW_TIME, OLD_MOVIE_ID, NEW_MOVIE_ID, OLD_ROOM_ID, NEW_ROOM_ID)
        VALUE(CURTIME(), 'UPDATE', NEW.PERFORMANCE_ID, OLD.DATE, NEW.DATE, OLD.TIME, NEW.TIME,
              OLD.MOVIE_ID, NEW.MOVIE_ID, OLD.ROOM_ID, NEW.ROOM_ID);
END;

